config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :users, only: %i[new create show]
  resources :groups, only: %i[index new create show]
  resources :payments, only: %i[index new create]
  get 'payments/index_no_group', to: 'payments#index_no_group'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :payments_groups, dependent: :destroy
  has_many :payments, through: :payments_groups
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 100 }
  has_one_attached :icon, dependent: :destroy
  validates :icon, blob: { content_type: :image }

  # Returns resized image
  def display_image
    icon.variant(resize_to_limit: [500, 500])
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :payments_groups, dependent: :destroy
  has_many :groups, through: :payments_groups
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 100 }
  validates :amount, presence: true, numericality: { less_than: 10_000 }
end

app/models/payments_group.rb
class PaymentsGroup < ApplicationRecord
  belongs_to :group
  belongs_to :payment
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :payments, foreign_key: 'author_id', dependent: :destroy
  has_many :groups, dependent: :destroy
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 100 }
  has_one_attached :avatar, dependent: :destroy
  validates :avatar, blob: { content_type: :image }

  # Returns resized image
  def display_image
    avatar.variant(resize_to_limit: [500, 500])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :set_cache_headers
  def set_cache_headers
    response.headers['Cache-Control'] = 'no-cache, no-store'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = 'Mon, 01 Jan 1990 00:00:00 GMT'
  end

  private

  def logged_in_or_back
    return if logged_in?

    flash[:danger] = ['Please login to continue']
    redirect_to root_url
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in_or_back

  def index
    @groups = Group.includes(:user).paginate(page: params[:page], per_page: 3).order(:name).with_attached_icon
  end

  def new
    @group = Group.new
  end

  def create
    group = Group.new(group_params)
    group.user_id = current_user.id
    if group.save
      flash[:success] = ['Group added']
      redirect_to groups_path
    else
      flash[:danger] = group.errors.full_messages
      redirect_back(fallback_location: new_group_path)
    end
  end

  def show
    @group = Group.includes(:payments, :user).find(params[:id])
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :logged_in_or_back
  def index
    @payments = Payment.includes(groups: [icon_attachment: :blob]).paginate(page: params[:page], per_page: 3)
      .where('author_id=?', current_user.id).joins(:groups)
  end

  def index_no_group
    @payments = Payment.includes(groups: [icon_attachment: :blob]).paginate(page: params[:page], per_page: 3)
      .where('author_id=?', current_user.id).left_outer_joins(:groups).where('groups.id IS NULL')
    render 'index'
  end

  def new
    @payment = Payment.new
  end

  def create
    payment = Payment.new(payment_params)
    payment.author_id = current_user.id
    if payment.save
      group_id = params[:payment][:group_id]
      PaymentsGroup.create(group_id: group_id, payment_id: payment.id) if group_id
      flash[:success] = ['Payment added']
      redirect_to payments_path
    else
      flash[:danger] = payment.errors.full_messages
      redirect_back(fallback_location: new_payment_path)
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :amount)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user&.authenticate(params[:session][:password])
      log_in @user
      flash[:success] = ['Successful Login']
      redirect_to @user
    else
      flash.now[:danger] = ["User doesn't exist"]
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    return unless logged_in?

    redirect_to current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = ['Successful Sign Up']
      log_in @user
      redirect_to @user
    else
      flash[:danger] = @user.errors.full_messages
      render 'new'
    end
  end

  def show
    @user = current_user
    return if logged_in?

    flash[:danger] = ['Access not allowed. Please login as this user first']
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def burger_path
    return current_user if logged_in?

    root_path
  end

  def creation_date(obj)
    obj.created_at.strftime('%d %b %Y')
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def display_icon(group)
    if group.icon.attached?
      image_tag group.display_image, class: 'group-img'
    else
      image_tag 'default-group-icon.png', class: 'group-img'
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
  def total_payments(payments)
    payments.inject(0) { |accum, payment| accum + payment.amount }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def display_avatar(user)
    if user.avatar.attached?
      image_tag user.display_image, class: 'avatar rounded-circle'
    else
      image_tag 'default-avatar.png', class: 'avatar rounded-circle'
    end
  end
end

app/views/groups/_group.html.erb
<div class="card w-75 mx-auto my-3">
  <div class="card-body d-flex justify-content-between">
    <%= link_to group, class: 'card-link' do %>
      <%= display_icon(group) %>
      <span><%= group.name %></span>
    <% end %>
  </div>
  <div class="card-footer">
    Created by <strong><%= group.user.name %></strong> on <%= creation_date(group) %>
  </div>
</div>

app/views/groups/index.html.erb
<% provide(:title, "Groups") %>
<%= render 'layouts/header'%>
<div class="d-flex justify-content-center mt-3">
  <%= will_paginate @groups, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>
<div class="space-for-new">
  <%= render @groups %>
</div>
<div class="bg-success py-3 fixed-bottom">
  <%= link_to 'New Group', new_group_path, type: "button", class: "btn btn-outline-light w-75 mx-auto d-block py-3"%>
</div>

app/views/groups/new.html.erb
<% provide(:title, "New group") %>
<%= render 'layouts/header'%>
<div class="card my-3 text-center">
  <div class="card-body px-5">
    <%= form_with model: @group, local: true do |f| %>
      <div class="md-form my-3">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name'%>
      </div>
      <div class="custom-file my-3">
        <%= f.file_field :icon, class: 'custom-file-input', direct_upload: true,accept: "image/jpeg, image/gif, image/png" %>
        <%= f.label :icon, class: 'custom-file-label' %>
      </div>
      <%= f.submit 'Create Group', class: 'btn btn-primary mt-3 p-3' %>
    <% end %>
  </div>
</div>

app/views/groups/show.html.erb
<% provide(:title, @group.name) %>
<%= render 'layouts/header'%>
<div class="card">
  <div class="card-body d-flex align-items-center">
    <%= display_icon(@group) %>
    <h1 class="ml-3">Group: <%= @group.name %></h1>
  </div>
  <div class="card-footer">
    Created by <%= @group.user.name %> on <%= creation_date(@group) %>
  </div>
</div>
<div class="card mt-3">
  <div class="card-body">
    <h2>Payments belonging to this group: </h2>
  </div>
</div>
<% @group.payments.each do |payment| %>
  <div class="card w-75 mx-auto my-3">
    <div class="card-body d-flex justify-content-between">
      <span><%= payment.name %></span>
      <strong>$<%= payment.amount%></strong>
    </div>
    <div class="card-footer">
      Created by <%= payment.author.name %> on <%= creation_date(payment) %>
    </div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-dark bg-primary py-4">
  <%= link_to burger_path, class: 'navbar-brand' do %>
    <i class="fas fa-bars fa-lg"></i>
  <% end %>
  <div class="navbar-nav text-white font-weight-bold">
    <%= yield(:title) %>
  </div>
  <div class="navbar-nav font-weight-bold">
    <%= link_to('Logout', logout_path, method: 'delete', class: 'nav-link') if logged_in? %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Primary Meta Tags -->
    <title><%= yield(:title).presence || 'Group Payments' %></title>
    <meta name="title" content="Group Payments">
    <meta name="description" content="A web app that allows you to group payments with your friends and family.">
    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://group-payments.herokuapp.com/">
    <meta property="og:title" content="Group Payments">
    <meta property="og:description" content="A web app that allows you to group payments with your friends and family.">
    <meta property="og:image" content="https://raw.githubusercontent.com/meronokbay/group-payments/master/app_screenshot.jpg">
    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://group-payments.herokuapp.com/">
    <meta property="twitter:title" content="Group Payments">
    <meta property="twitter:description" content="A web app that allows you to group payments with your friends and family.">
    <meta property="twitter:image" content="https://raw.githubusercontent.com/meronokbay/group-payments/master/app_screenshot.jpg">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# Google fonts %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">
    <%# Font awesome %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <% flash.each do |type, msg| %>
      <ul class="alert alert-<%= type %> mb-0">
        <% msg.each do |m| %>
          <%= content_tag :li, m %>
        <% end %>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/payments/_payment.html.erb
<div class="card w-75 mx-auto my-3">
  <div class="card-body d-flex justify-content-between align-items-center">
    <div>
      <%= display_icon(payment.groups.take) if payment.groups.any? %>
      <%= payment.name %>
    </div>
    <strong>$<%= payment.amount%></strong>
  </div>
  <div class="card-footer">
    <%= creation_date(payment) %>
  </div>
</div>

app/views/payments/index.html.erb
<% provide(:title, "Payments") %>
<%= render 'layouts/header'%>
<div class="card">
  <div class="card-body d-flex justify-content-between">
    <span>Total Amount</span>
    <strong>$<%= total_payments(@payments) %></strong>
  </div>
</div>
<div class="d-flex justify-content-center mt-3">
  <%= will_paginate @payments, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>
<div class="space-for-new">
  <%= render @payments %>
</div>
<div class="bg-success py-3 fixed-bottom">
  <%= link_to 'New Payment', new_payment_path, type: "button", class: "btn btn-outline-light w-75 mx-auto d-block py-3"%>
</div>

app/views/payments/new.html.erb
<% provide(:title, "New Payment") %>
<%= render 'layouts/header'%>
<div class="card my-3 text-center">
  <div class="card-body px-5">
    <%= form_with model: @payment, local: true do |f| %>
      <div class="md-form my-3">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name'%>
      </div>
      <div class="md-form my-3">
        <%= f.number_field :amount, class: 'form-control', placeholder: 'Amount'%>
      </div>
      <div class="input-group my-3">
        <div class="input-group-prepend">
          <%= f.label :group_id, class: 'input-group-text' %>
        </div>
        <%= f.collection_select(:group_id, Group.all, :id, :name, {include_blank: true}, {class: 'custom-select'}) %>
      </div>
      <%= f.submit 'Submit Payment', class: 'btn btn-primary mt-3 p-3' %>
    <% end %>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="contaier">
  <h1 class="home-title text-center">Group Payments</h1>
</div>
<%= link_to 'Login', login_path, class: 'nav-link btn btn-primary mx-3 py-3'%>
<%= link_to 'Signup', signup_path, class: 'nav-link btn mx-3 py-3' %>

app/views/users/new.html.erb
<% provide(:title, "Signup") %>
<%= render 'layouts/header'%>
<div class="card my-3 text-center">
  <div class="card-body px-5">
    <%= form_with model: @user, local: true do |f| %>
      <div class="md-form mb-3">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name'%>
      </div>
      <div class="md-form mb-3">
        <%= f.password_field :password, class: 'form-control', placeholder: 'Password (Minimum 6 characters)' %>
      </div>
      <div class="custom-file mb-3">
        <%= f.file_field :avatar, class: 'custom-file-input', direct_upload: true, accept: "image/jpeg, image/gif, image/png" %>
        <%= f.label :avatar, class: 'custom-file-label' %>
      </div>
      <%= f.submit 'Signup', class: 'btn btn-primary p-3' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="bg-primary vh-100 text-white">
  <div class="py-3 text-center">
    <%= display_avatar(@user) %>
    <h1><%= @user.name %></h1>
  </div>
  <ul class="list-group my-5">
    <li class="list-group-item bg-primary">
      <i class="fas mr-3 fa-globe"></i>
      <%= link_to "All my payments", payments_path, class: 'text-white' %>
    </li>
    <li class="list-group-item bg-primary">
      <i class="fas mr-3 fa-map-marker-alt"></i>
      <%= link_to 'All my external payments', payments_index_no_group_path, class: 'text-white' %>
    </li>
    <li class="list-group-item bg-primary">
      <i class="fas mr-3 fa-user-friends"></i>
      <%= link_to 'All groups', groups_path, class: 'text-white' %>
    </li>
    <li class="list-group-item bg-primary">
      <i class="fas mr-3 fa-sign-out-alt"></i>
      <%= link_to 'Logout', logout_path, method: 'delete', class: 'text-white' %>
    </li>
  </ul>
</div>